#! /bin/bash
set -x -e -o pipefail

BRANCH="${1:develop}"
REMOTE="${2:origin}"

echo "update branch ${BRANCH} from remote ${REMOTE}"

git fetch -p "${REMOTE}" "${BRANCH}":"${BRANCH}"
git rebase "${BRANCH}"
SINGLE=true git pb "${BRANCH}" "${REMOTE}"
