#! /bin/bash
set -e
set -o pipefail

VERBOSITY=1
THRESHOLD=INFO

MASTER=master
ORIG_BRANCH=$(git rev-parse --abbrev-ref HEAD)
while [ $# -gt 0 ]
do
  PR=${1}
  shift
  SINGLE=true git-push-branches
  PR_SHA=$(hub pr show -f "%sH" ${PR})
  PR_BRANCH=$(hub pr show -f "%H" ${PR})
  git checkout -q ${PR_BRANCH}
  # Wait for tests then press the submit button
  submit-pr --source-owner=hpe-hcss --source-repo=cluster-api-provider-glhc --login=bretmckee  --stderrthreshold=${THRESHOLD} -v=${VERBOSITY} --pr=${PR}
  # change the base of any PR whose base is this branch to master
  rebase-prs --source-owner=hpe-hcss --source-repo=cluster-api-provider-glhc --login=bretmckee  --stderrthreshold=${THRESHOLD} -v=${VERBOSITY} --pr=${PR}
  # clean up the local branch
  git checkout -q ${ORIG_BRANCH}
  git fetch origin ${MASTER}:${MASTER}
  git rebase --onto ${MASTER} ${PR_SHA}
  git push --force
done
